FROM daocloud.io/node:8.5-alpine

MAINTAINER daizch <daizech@gmail.com>

RUN mkdir -p /data/freelog-i18n-service

WORKDIR /data/freelog-i18n-service

COPY . /data/freelog-i18n-service

RUN npm config set registry https://registry.npm.taobao.org 
RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5110

EXPOSE 5110

CMD [ "npm", "start" ]